name: PRECORSIA front-end server-side tests
on:
  push:
    branches:
      - main

jobs:
  build-PRECORSIA:
    name: Build PRECORSIA
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure nodejs
      uses: actions/setup-node@v2
      with: 
        node-version: '14'
    
    - name: Build
      run: |
        npm install

  test-PRECORSIA:
    name: Test PRECORSIA
    needs: build-PRECORSIA
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure nodejs
      uses: actions/setup-node@v2
      with: 
        node-version: '14'
    
    - name: Test
      run: |
        npm install
        npm run test:report

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mochawesome-report
        path: mochawesome-report/