name: PRECORIA front-end server-side tests
on:
  push:
    branches:
      - main

jobs:
  build-todo-app:
    name: PRECORSIA front-end server-side tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure nodejs
      uses: actions/setup-node@v2
      with: 
        node-version: '14'
    
    - name: Build and test
      run: |
        npm install
        npm run test